name: ci

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x.x

      - name: Log versions
        run: |
          deno --version
      - name: Format TS
        run: |
          # deno lint
          deno fmt --check
      - name: Test TS
        run: deno test -A
